[package]
name = "wikipedia-parser"
version = "0.1.0"
authors = ["Niumlaque <niumlaque@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
scraper = "0.11.0"
